import { Geist, Geist_Mono, Bebas_Neue } from "next/font/google";
import "locomotive-scroll/dist/locomotive-scroll.css";
import { ViewTransitions } from "next-view-transitions";
import localFont from "next/font/local";
import "./globals.css";
import ScrollWrapper from "@/components/ScrollerWrapper/ScrollerWrapper";

const MariupolBold = localFont({
  src: "../public/fonts/Mariupol-Bold.ttf",
  weight: "700",
  style: "normal",
  display: "swap",
});

const bebas = localFont({
  src: "../public/fonts/bebas.ttf",
  weight: "700",
  style: "normal",
  display: "swap",
});

const bebasRegular = localFont({
  src: "../public/fonts/bebas.ttf",
  weight: "200",
  style: "normal",
  display: "swap",
});

const bahnschrift = localFont({
  src: "../public/fonts/BAHNSCHRIFT.ttf",
  weight: "800",
  style: "normal",
  display: "swap",
});
const bahnschriftRegular = localFont({
  src: "../public/fonts/BAHNSCHRIFT.ttf",
  weight: "400",
  style: "normal",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body
          className={`${bebasRegular.className} ${bahnschrift.className} ${bahnschriftRegular.className} ${bebas.className}`}
        >
          <ScrollWrapper>{children}</ScrollWrapper>
        </body>
      </html>
    </ViewTransitions>
  );
}
