import { Geist, Geist_Mono, Bebas_Neue } from "next/font/google";
import { cookies } from "next/headers";
import "locomotive-scroll/dist/locomotive-scroll.css";
import { ViewTransitions } from "next-view-transitions";
import localFont from "next/font/local";
import ScrollWrapper from "@/components/ScrollerWrapper/ScrollerWrapper";
import "./globals.css";
import { MenuProvider } from "@/context/MenuContext";
import PageTransitionHandler from "@/components/PageTransitionHandler/PageTransitionHandler";
import { ModalProvider } from "@/context/ModalContext";
import UTMCookieSaver from "@/components/UTMSaver/UTMSaver";

const MariupolBold = localFont({
  src: "../public/fonts/Mariupol-Bold.ttf",
  weight: "700",
  style: "normal",
  display: "swap",
});

const bebas = localFont({
  src: "../public/fonts/bebas.ttf",
  weight: "700",
  style: "normal",
  display: "swap",
});

const bebasRegular = localFont({
  src: "../public/fonts/bebas.ttf",
  weight: "200",
  style: "normal",
  display: "swap",
});

const bahnschrift = localFont({
  src: "../public/fonts/BAHNSCHRIFT.ttf",
  weight: "800",
  style: "normal",
  display: "swap",
});
const bahnschriftRegular = localFont({
  src: "../public/fonts/BAHNSCHRIFT.ttf",
  weight: "400",
  style: "normal",
  display: "swap",
});

const bahnschriftThin = localFont({
  src: "../public/fonts/BAHNSCHRIFT.ttf",
  weight: "200",
  style: "normal",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLoyout({ children, params }) {
  const cookieStore = await cookies();
  const locale = cookieStore.get("NEXT_LOCALE")?.value ?? "en";

  return (
    <html lang={locale}>
      <ViewTransitions>
        <body
          className={`${bebasRegular.className} ${bahnschrift.className} ${bahnschriftRegular.className} ${bahnschriftThin.className} ${bebas.className}`}
        >
          <PageTransitionHandler></PageTransitionHandler>
          <UTMCookieSaver />
          <ModalProvider>
            <ScrollWrapper>
              <MenuProvider>{children} </MenuProvider>
            </ScrollWrapper>
          </ModalProvider>
        </body>
      </ViewTransitions>
    </html>
  );
}
